version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: assemblydb
      MYSQL_USER: sauravS
      MYSQL_PASSWORD: saurav@simmi
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    image: assembly-language-app
    container_name: AssemblyLanguageApplication
    build: .
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      mysql:
        condition: service_healthy

networks:
  mynetwork:
    driver: bridge